[project]
name = "spacetraders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "inquirer>=3.4.1",
    "pyfiglet>=1.0.4",
    "pyyaml>=6.0.3",
    "tabulate2>=1.10.2",
    "yaspin>=3.4.0",
]
